tutorial/books/urls.py
from django.urls import path
from . import views

app_name = 'books'

urlpatterns = [
    path('', views.BooksModelView.as_view(), name='index'),
    path('make_record_view/', views.MakeRecordView.as_view(), name='make_record_view'),
    path('make_record/', views.make_record, name='make_record'),
    path('book/', views.BookList.as_view(), name='book_list'),
    path('author/', views.AuthorList.as_view(), name='author_list'),
    path('publisher/', views.PublisherList.as_view(), name='publisher_list'),
    path('book/<int:pk>/', views.BookDetail.as_view(), name='book_detail'),
    path('author/<int:pk>/', views.AuthorDetail.as_view(), name='author_detail'),
    path('publisher/<int:pk>/', views.PublisherDetail.as_view(), name='publisher_detail'),
]

tutorial/polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('make_question/', views.make_question, name='make_question'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/result/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

tutorial/two_site/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
    path('books/', include('books.urls')),
    path('', views.HomeView.as_view(), name='home'),
]

tutorial/books/models.py
from django.db import models

class Book(models.Model):
    title = models.CharField(max_length=100)
    authors = models.ManyToManyField('Author')
    publisher = models.ForeignKey('Publisher', on_delete=models.CASCADE)
    publication_field = models.DateField()

    def __str__(self):
        return self.title

class Author(models.Model):
    salutation = models.CharField(max_length=100)
    name = models.CharField(max_length=50)
    email = models.EmailField()

    def __str__(self):
        return self.name

class Publisher(models.Model):
    name = models.CharField(max_length=50)
    address = models.CharField(max_length=200)
    website = models.URLField()

    def __str__(self):
        return self.name

tutorial/polls/models.py
from django.db import models

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self) -> str:
        return self.question_text

class Choice(models.Model):
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)

    def __str__(self) -> str:
        return self.choice_text

tutorial/books/views.py
from django.shortcuts import render, redirect
from django.views import generic
from django.utils import timezone
from django.urls import reverse
from books.models import Author, Book, Publisher

class BooksModelView(generic.TemplateView):
    template_name = 'books/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['model_list'] = ['Book', 'Author', 'Publisher']
        return context

class MakeRecordView(generic.TemplateView):
    template_name = 'books/make_record.html'

class BookList(generic.ListView):
    model = Book

class AuthorList(generic.ListView):
    model = Author

class PublisherList(generic.ListView):
    model = Publisher

class BookDetail(generic.DetailView):
    model = Book

class AuthorDetail(generic.DetailView):
    model = Author

class PublisherDetail(generic.DetailView):
    model = Publisher

def make_record(request):
    if request.method == 'POST':
        book = Book()
        book.publication_field = timezone.now()

        author = Author()
        publisher = Publisher()
        book.title = request.POST['book_title']
        book.authors.add(author)
        book.publisher = publisher
        book.publication_field = timezone.now()

        author.salutation = request.POST['author_salutation']
        author.name = request.POST['author_name']
        author.email = request.POST['author_email']

        publisher.name = request.POST['publisher_name']
        publisher.address = request.POST['publisher_address']
        publisher.website = request.POST['publisher_website']

        author.save()
        publisher.save()
        book.save()


        return redirect(reverse('books:index'))

tutorial/polls/views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from polls.models import Question, Choice

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        return Question.objects.order_by('-pub_date')[:5]

# class MakeQuestionView(generic.TemplateView):
#     template_name = 'polls/make_question.html'

class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

    # def get_object(self):
    #     object = get_object_or_404(Question, id=self.kwargs['id'])
    #     return object


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

def make_question(request):
    if request.method == 'GET':
        return render(request, 'polls/make_question.html')
    if request.method == 'POST':
        question = Question()
        question.question_text = request.POST['question_text']
        question.pub_date = timezone.now()
        choice_1 = Choice()
        choice_2 = Choice()
        choice_3 = Choice()

        choice_1.choice_text = request.POST['choice_1']
        choice_2.choice_text = request.POST['choice_2']
        choice_3.choice_text = request.POST['choice_3']
        choice_1.votes = 0
        choice_2.votes = 0
        choice_3.votes = 0
        choice_1.question = question
        choice_2.question = question
        choice_3.question = question

        question.save()
        choice_1.save()
        choice_2.save()
        choice_3.save()
        return redirect(reverse('polls:index'))


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html',
        {'question' : question,
         'error_message' : 'You didn`t select a choice.'})

    else:
        selected_choice.votes += 1
        selected_choice.save()

        return HttpResponseRedirect(reverse('polls:results', args=(question.id, )))

tutorial/two_site/views.py
from django.views.generic.base import TemplateView

class HomeView(TemplateView):
    template_name = 'home.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['app_list'] = ['polls', 'books']
        return context

tutorial/books/templates/books/author_detail.html
{% extends 'base_books.html' %}

{% block content %}
  <h1>{{ author.name }}</h1>
  <p>{{ author.salutation }}</p>
  <li>Email :
    {{ author.email }}</li>

{% endblock content %}

tutorial/books/templates/books/author_list.html
{% extends 'base_books.html' %}

{% block content %}
  <h2>Author List</h2>
  <ul>
    {% for author in author_list %}
      <li>
        <a href="{% url 'books:author_detail' author.id %}">{{ author.name }}</a>
      </li>
    {% endfor %}
  </ul>
{% endblock content %}

tutorial/books/templates/books/book_detail.html
{% extends 'base_books.html' %}

{% block content %}
  <h1>{{ book.title }}</h1>

  <br>

  <li>Authors :
    {% for author in book.authors.all %}
      {{ author }}
      {% if not forloop.last %},
      {% else %}
      {% endif %}
    {% endfor %}
  </li>

  <li>Publisher :
    {{ book.publisher }}</li>
  <li>Publication Date :
    {{ book.publication_date }}</li>
{% endblock content %}

tutorial/books/templates/books/book_list.html
{% extends 'base_books.html' %}

{% block content %}
  <h2>Book List</h2>
  <ul>
    {% for book in book_list %}
      <li>
        <a href="{% url 'books:book_detail' book.id %}">{{ book.title }}</a>
      </li>
    {% endfor %}
  </ul>
{% endblock content %}

tutorial/books/templates/books/index.html
{% extends 'base_books.html' %}

{% block content %}
  <h2>Books Management System</h2>
  <h3>
    <strong>
      <a href="{% url 'books:make_record_view' %}">Make New Book Record!</a>
    </strong>
  </h3>
  <ul>
    {% for modelname in model_list%}
      <li>{% with "books:"|add:modelname|lower|add:"_list" as urlvar %}
        <a href="{% url urlvar %}">{{ modelname }}</a>
        {% endwith %}</li>
    {% endfor %}
  </ul>
{% endblock content %}

tutorial/books/templates/books/make_record.html
{% extends 'base_books.html' %}

{% block content %}
  <h2>Make New Book Data</h2>
  <form action="{% url 'books:make_record' %}" method='post'>
    {% csrf_token %}
    <label for="New Book title">New Book title:
    </label>
    <input name="book_title" type="text" id="book_title">
    <br>
    <label for="Author salutation">Author salutation:
    </label>
    <input type="text" name="author_salutation" id="author_salutation">
    <br>
    <label for="Author name">Author name:
    </label>
    <input type="text" name="author_name" id="author_name">
    <br>
    <label for="Author email">Author email:
    </label>
    <input type="text" name="author_email" id="author_email">
    <br>
    <label for="Publisher name">Publisher name:
    </label>
    <input type="text" name="publisher_name" id="publisher_name">
    <br>
    <label for="Publisher address">Publisher address:
    </label>
    <input type="text" name="publisher_address" id="publisher_address">
    <br>
    <label for="Publisher website">Publisher website:
    </label>
    <input type="text" name="publisher_website" id="publisher_website">
    <br>
    <input type="submit" value="CREATE">
  </form>
{% endblock content %}

tutorial/books/templates/books/publisher_detail.html
{% extends 'base_books.html' %}

{% block content %}
  <h1>{{ publisher.name }}</h1>
  <p>{{ publisher.website }}</p>
  <li>Address:
    {{ publisher.address }}</li>
{% endblock content %}

tutorial/books/templates/books/publisher_list.html
{% extends 'base_books.html' %}

{% block content %}
  <h2>Publishers List</h2>
  <ul>
    {% for publisher in publisher_list %}
      <li>
        <a href="{% url 'books:publisher_detail' publisher.id %}">{{ publisher.name }}</a>
      </li>
    {% endfor %}
  </ul>
{% endblock content %}

tutorial/polls/templates/polls/detail.html
{% extends 'base_polls.html' %}

{% block content %}
  <h1>{{ question.questin_text }}</h1>
  {% if error_message %}
    <p>
      <strong>{{ error_message }}</strong>
    </p>
  {% endif %}

  <form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
      <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}"/>
      <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    {% endfor %}
    <input type="submit" value="Vote">
  </form>
{% endblock content %}

tutorial/polls/templates/polls/index.html
{% extends 'base_polls.html' %}

{% block content %}
  <h2>Polls Question List</h2>

  <h3>
    <a href="{% url 'polls:make_question' %}">Make Question!</a>
  </h3>
  {% if latest_question_list %}
    <ul>
      {% for question in latest_question_list %}
        <li>
          <a href="{% url 'polls:detail' question.id %} ">{{ question.question_text }}</a>
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>No polls are AVAILABLE!</p>
  {% endif %}

{% endblock content %}

tutorial/polls/templates/polls/make_question.html
{% extends 'base_polls.html' %}

{% block content %}
  <form action="{% url 'polls:make_question' %}" method='post'>
    {% csrf_token %}
    <label for="New Question">New Question:
    </label>
    <input id="question_text" type="text" name="question_text" maxlength="100">
    <br>
    <h3>Please Add LEAST THREE CHOICES for your question!</h3>
    <label for="choice_1">choice One:</label>
    <input id="choice_1" type="text" name="choice_1" maxlength="100">
    <br>
    <label for="choice_2">choice Two:</label>
    <input id="choice_2" type="text" name="choice_2" maxlength="100">
    <br>
    <label for="choice_3">choice Three:</label>
    <input id="choice_3" type="text" name="choice_3" maxlength="100">
    <br>
    <input type="submit" value="CREATE">
  </form>
{% endblock content %}

tutorial/polls/templates/polls/results.html
{% extends 'base_polls.html' %}

{% block content %}
  <h1>{{ question.question_text }}</h1>

  <ul>
    {% for choice in question.choice_set.all %}
      <li>{{ choice.choice_text }}
        --
        {{ choice.votes }}
        vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
  </ul>

  <a href="{% url 'polls:detail' question.id %}">Vote Again?</a>
{% endblock content %}

tutorial/templates/base.html
<!DOCTYPE html>
<html lang="en">

  <head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'admin/css/base.css' %}"/>
    <title>
      {% block title %}Amazing Site{% endblock title %}
    </title>
  </head>

  <body>
    <div id='sidebar'>
      {% block sidebar %}
        <ul>
          <li>
            <a href="/">Project Home</a>
          </li>
          <li>
            <a href="/admin/">Admin</a>
          </li>
        </ul>
      {% endblock sidebar %}
      <br>
    </div>

    <div id='content'>
      {% block content %}{% endblock content %}
    </div>

  </body>

</html>

tutorial/templates/base_books.html
{% extends 'base.html' %}

<title>
  {% block title %}Book Application{% endblock title %}
</title>

{% block sidebar %}
  {{ block.super }}
  <ul>
    <li>
      <a href="/polls/">Books Home</a>
    </li>
  </ul>
{% endblock sidebar %}

tutorial/templates/base_polls.html
{% extends 'base.html' %}

<title>
  {% block title %}Poll Application{% endblock title %}
</title>

{% block sidebar %}
  {{ block.super }}
  <ul>
    <li>
      <a href="/polls/">Polls Home</a>
    </li>
  </ul>
{% endblock sidebar %}

tutorial/templates/home.html
{% extends 'base.html' %}

{% block content %}
  <h2>K.Kong Django Applications</h2>
  <ul>
    {% for appname in app_list %}
      {% with appname|add:":"|add:"index" as urlvar %}
      <li>
        <a href="{% url urlvar %}">{{ appname }}</a>
      </li>
      {% endwith %}
    {% endfor %}
  </ul>
{% endblock content %}