hseed/board/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'board'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
    path('question/create/', views.question_create, name='question_create'),
]

hseed/common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

hseed/config/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from board import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('board/', include('board.urls')),
    path('common/', include('common.urls')),
    path('', views.index, name='index'),
]

hseed/board/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import query

class Question(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()

    def __str__(self) -> str:
        return self.subject

class Answer(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()

    def __str__(self) -> str:
        return self.content

hseed/common/models.py
from django.db import models

# Create your models here.

hseed/board/forms.py
from django import forms
from .models import Answer, Question

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['subject', 'content']
        labels ={
            'subject' : '제목',
            'content' : '내용'
        }

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {
            'content' : '답변내용',
        }

hseed/common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class UserForm(UserCreationForm):
    email = forms.EmailField(label='이메일')

    class Meta:
        model = User
        fields = ("username", "password1", "password2", "email")

hseed/board/views.py
from django.contrib.auth import login
from django.core import paginator
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from django.core.paginator import Paginator

from .forms import AnswerForm

from .models import Answer, Question
from .forms import QuestionForm
from django.contrib.auth.decorators import login_required

def index(request):
    page = request.GET.get('page', 1)
    question_list = Question.objects.order_by('-create_date')

    paginator = Paginator(question_list, 10)
    page_obj = paginator.get_page(page)
    context = {'question_list': page_obj}
    
    return render(request, 'board/question_list.html', context)

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}
    return render(request, 'board/question_detail.html', context)

@login_required(login_url='common:login')
def answer_create(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.method == 'POST':
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user
            answer.create_date = timezone.now()
            answer.question = question
            answer.save()
            return redirect('board:detail', question_id=question.id)
    else:
        form = AnswerForm()
    context = {'question' : question, 'form' : form}
    return render(request, 'board/question_detail.html', context)

@login_required(login_url="common:login")
def question_create(request):
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user
            question.create_date = timezone.now()
            question.save()
            return redirect('board:index')
    else:
        form = QuestionForm()
    context = {'form' : form}

    return render(request, 'board/question_form.html', context)

hseed/common/views.py
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from .forms import UserForm

def signup(request):
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('index')
    else:
        form = UserForm()

    return render(request, 'common/signup.html', {'form': form})

hseed/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">

  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'bootstrap.min.css' %}" type="text/css">
    <title>Welcome, HSEEDS :)</title>
  </head>

  <body>
    {% include "navbar.html" %}
    {% block content %}{% endblock content %}
    <!-- jQuery JS-->
    <script src="{% static 'jquery-3.6.0.min.js' %}"></script>
    <!-- Bootstrap JS-->
    <script src="{% static 'bootstrap.min.js' %}"></script>
  </body>

</html>

hseed/templates/board/question_detail.html
{% extends 'base.html' %}
{% block content %}

  <div class="container my-3">
    <h2 class="border-bottom py-2">{{ question.subject }}</h2>
    <div class="card my-3">
      <div class="card-body">
        <div class="card-text" style="white-space: pre-line">{{ question.content }}</div>
        <div class="d-flex justify-content-end">
          <div class="badge badge-light p-2 text-left">
            <div class="mb-2">{{ question.author.username }}</div>
            <div>
              {{ question.create_date }}
            </div>
          </div>
        </div>
      </div>
    </div>
    <h5 class="border-bottom my-3 py-2">{{ question.answer_set.count }}개의 답변이 있습니다.</h5>
    {% for answer in question.answer_set.all %}
      <div class="card my-3">
        <div class="card-body">
          <div class="card-text" style="white-space: pre-line;">{{ answer.content }}</div>
          <div class="d-flex justify-content-end">
            <div class="badge badge-light p-2 text-left">
              <div class="mb-2">{{ answer.author.username }}</div>
              <div>{{ answer.create_date }}</div>
            </div>
          </div>
        </div>
      </div>
    {% endfor %}
    <form action="{% url 'board:answer_create' question.id %}" method="post" class="my-3">
      {% csrf_token %}
      {% if form.errors %}
        <div class="alert alert-danger" role="alert">
          {% for field in form %}
            {% if field.errors %}
              <strong>{{ field.label }}</strong>
              {{ field.errors }}
            {% endif %}
          {% endfor %}
        </div>
      {% endif %}
      <div class="form-group">
        <textarea {% if not user.is_authenticated %} disabled {% endif %} name="content" id="content" rows="10" class="form-control"></textarea>
      </div>
      <input type="submit" value="답변등록" class="btn btn-primary">
    </form>
  </div>
{% endblock content %}

hseed/templates/board/question_form.html
{% extends 'base.html' %}

{% block content %}
  <div class="container">
    <h5 class="my-3 border-bottom pb-2">질문등록</h5>
    <form method='post' class='post-form my-3'>
      {% csrf_token %}
      {% if form.errors %}
        <div class="alert alert-danger" role="alert">
          {% for field in form %}
            {% if field.errors %}
              <strong>{{ field.label }}</strong>
              {{ field.errors }}
            {% endif %}
          {% endfor %}
        </div>
      {% endif %}
      <div class="form-group">
        <label for="subject">제목</label>
        <input type="text" class="form-control" name="subject" id="subject" value="{{ form.subject.value|default_if_none:'' }}">
      </div>
      <div class="form-group">
        <label for="content">내용</label>
        <textarea class="form-control" name="content" id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
      </div>
      <button type='submit' class='btn btn-primary'>저장하기</button>
    </form>
  </div>
{% endblock content %}

hseed/templates/board/question_list.html
{% extends 'base.html' %}
{% load board_filter %}
{% block content %}

  <div class="container my-3">
    <table class="table">
      <thead>
        <tr class="text-center thead-dark">
          <th>번호</th>
          <th style="width:50%">제목</th>
          <th>글쓴이</th>
          <th>작성일시</th>
        </tr>
      </thead>
      <tbody>
        {% if question_list %}
          {% for question in question_list %}
            <tr class="text-center">
              <td>
                {{ question_list.paginator.count|sub:question_list.start_index|sub:forloop.counter0|add:1 }}
              </td>
              <td class="text-left">
                <a href="{% url 'board:detail' question.id %}">{{ question.subject }}</a>
                {% if question.answer_set.count > 0 %}
                <span class="text-danger small ml-2">{{ question.answer_set.count }}</span>
                {% endif %}
              </td>
              <td>{{ question.author.username }}</td>
              <td>{{ question.create_date }}</td>
            </tr>
          {% endfor %}
        {% else %}
          <td colspan='3'>질문이 없습니다.</td>
        {% endif %}
      </tbody>
    </table>
    <!-- paging -->
    <ul class="pagination justify-content-center">
      {% if question_list.has_previous %}
        <li class="page-item">
          <a href="?page={{ question_list.previous_page_number }}" class="page-link">이전</a>
        </li>
      {% else %}
        <li class=" page-item disabled">
          <a href="#" class="page-link" tabindex="-1" aria-disabled="true">이전</a>
        </li>
      {% endif %}
      {% for page_number in question_list.paginator.page_range %}
        {% if page_number >= question_list.number|add:-5 and page_number <= question_list.number|add:5 %}
          {% if page_number == question_list.number %}
            <li class="page-item active" aria-current="page">
              <a href="?page={{ page_number }}" class="page-link">{{ page_number }}</a>
            </li>
          {% else %}
            <li class="page-item">
              <a href="?page={{ page_number }}" class="page-link">{{ page_number }}</a>
            </li>
          {% endif %}
        {% endif %}
      {% endfor %}
      {% if question_list.has_next %}
        <li class="page-item">
          <a href="?page={{ question_list.next_page_number }}" class="page-link">다음</a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <a href="#" class="page-link" tabindex="-1" aria-disabled="true">다음</a>
        </li>
      {% endif %}
    </ul>

    <a href="{% url 'board:question_create' %}" class="btn btn-primary">질문 등록하기</a>
  </div>

{% endblock content %}

hseed/templates/common/login.html
{% extends "base.html" %}
{% block content %}
  <div class="container my-3">
    <div class="row">
      <div class="col-4">
        <h4>로그인</h4>
      </div>
      <div class="col-8 text-right">
        <span>또는
          <a href="{% url 'common:signup' %}">계정을 만드세요.</a>
        </span>
      </div>
    </div>
    <form method="post" class="post-form" action="{% url 'common:login' %}">
      {% csrf_token %}
      <input type="hidden" name="next" value="{{ next }}">
      {% include "form_errors.html" %}
      <div class="form-group">
        <label for="username">사용자ID</label>
        <input type="text" class="form-control" name="username" id="username" value="{{ form.username.value|default_if_none:'' }}">
      </div>
      <div class="form-group">
        <label for="password">비밀번호</label>
        <input type="password" class="form-control" name="password" id="password" value="{{ form.password.value|default_if_none:'' }}">
      </div>
      <button type="submit" class="btn btn-primary">로그인</button>
    </form>
  </div>
{% endblock %}

hseed/templates/common/signup.html
{% extends "base.html" %}
{% block content %}
  <div class="container my-3">
    <div class="row my-3">
      <div class="col-4">
        <h4>계정생성</h4>
      </div>
      <div class="col-8 text-right">
        <span>또는
          <a href="{% url 'common:login' %}">로그인 하세요.</a>
        </span>
      </div>
    </div>
    <form method="post" class="post-form" action="{% url 'common:signup' %}">
      {% csrf_token %}
      {% include "form_errors.html" %}
      <div class="form-group">
        <label for="username">사용자 이름</label>
        <input type="text" class="form-control" name="username" id="username" value="{{ form.username.value|default_if_none:'' }}">
      </div>
      <div class="form-group">
        <label for="password1">비밀번호</label>
        <input type="password" class="form-control" name="password1" id="password1" value="{{ form.password1.value|default_if_none:'' }}">
      </div>
      <div class="form-group">
        <label for="password2">비밀번호 확인</label>
        <input type="password" class="form-control" name="password2" id="password2" value="{{ form.password2.value|default_if_none:'' }}">
      </div>
      <div class="form-group">
        <label for="email">이메일</label>
        <input type="text" class="form-control" name="email" id="email" value="{{ form.email.value|default_if_none:'' }}">
      </div>
      <button type="submit" class="btn btn-primary">생성하기</button>
    </form>
  </div>
{% endblock %}

hseed/templates/form_errors.html
{% if form.errors %}
  {% for field in form %}
    {% for error in field.errors %}
      <!-- 필드 오류를 출력한다. -->
      <div class="alert alert-danger">
        <strong>{{ field.label }}</strong>
        {{ error }}
      </div>
    {% endfor %}
  {% endfor %}
  {% for error in form.non_field_errors %}
    <!-- 넌필드 오류를 출력한다. -->
    <div class="alert alert-danger">
      <strong>{{ error }}</strong>
    </div>
  {% endfor %}
{% endif %}

hseed/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
  <a href="{% url 'board:index' %}" class="navbar-brand">HSEED Board</a>
  <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        {% if user.is_authenticated %}
          <a href="{% url 'common:logout' %}" class="nav-link">{{ user.username }}
            (로그아웃)</a>
        {% else %}
          <a href="{% url 'common:login' %}" class="nav-link">로그인</a>
        {% endif %}
      </li>
    </ul>
  </div>
</nav>